name: workflow-name
on: push

jobs:
  job-name:
    runs-on: ubuntu-latest
    services:
      service-name-1:
        image: tcardonne/github-runner:latest
       

      service-name-2:
        image: tcardonne/github-runner:latest
       

    steps:
      - name: Get from service-1
        run: http://192.168.10.200/

      - name: Get from service-2
        run: http://192.168.10.200/

