name: workflow-name
on: push

jobs:
  job-name:
    runs-on: ubuntu-latest
    services:
      service-name-1:
        image: tcardonne/github-runner:latest
       

      service-name-2:
        image: tcardonne/github-runner:latest
       

    steps:
      - name: Get from service-1
        run: http://localhost/api/users

      - name: Get from service-2
        run: http://localhost/api/items

